### ISSUE TITLE
extensions-compose should be renamed due to Gradle limitation with new library catalog declaration

### ISSUE THREAD

**Issue by SamuelMarks** [arkivanov/Decompose#783]
Details: https://github.com/gradle/gradle/issues/21593

Following your guide: https://arkivanov.github.io/Decompose/getting-started/installation/

Added:
```kotlin
// composeApp/build.gradle.kts
implementation("com.arkivanov.decompose:extensions-compose:3.2.0-beta01")
```

Which the Android Studio suggested I rewrite:
<img width="1247" alt="Screenshot 2024-09-22 at 1 05 32 pm" src="https://github.com/user-attachments/assets/7351f24c-9a5c-4924-81af-75f8bdf806f9">

Creating:
```kotlin
// composeApp/build.gradle.kts
implementation(libs.extensions.compose)
```
```toml
# gradle/libs.versions.toml
[versions]
# others omitted for brevity
decomposeVersion = "3.2.0-beta01"

[libraries]
# others omitted for brevity
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decomposeVersion" }
extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decomposeVersion" }
```

Leaving me with this error:
```
Method org/gradle/accessors/dm/LibrariesForLibs_Decorated.getExtensions()Lorg/gradle/api/plugins/ExtensionContainer; is abstract
```
