### ISSUE TITLE
import object field 'org_jetbrains_skia_DirectContext__1nFlushDefault' is not a Function

### ISSUE THREAD

**Issue by SamuelMarks** [arkivanov/Decompose#785]
Occurs when running  `wasmJsBrowserRun -t` on the latest Compose Wizard generated codebase with the following modifications:
```toml
[versions]
decompose = "3.2.0-beta01"
essenty = "2.2.0-beta01"

[libraries]
decompose-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
```

(also tried with the older syntax)

```gradle
kotlin {
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            export(libs.decompose.decompose)
            export(libs.essenty.lifecycle)
        }
    }
```

```gradle
kotlin {
    sourceSets {
        commonMain.dependencies {
            api(libs.decompose.decompose)
            api(libs.decompose.extensions.compose)
            api(libs.essenty.lifecycle)
        }
```

Using the older/stable versions worked without err:
```toml
decompose = "3.1.0"
essenty = "2.1.0"
```
